---
# a task to verify we can build protobufs for the plan-core library

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: plan-core-src
    path: plan-core
  - name: plan-protobufs-src
    path: plan-protobufs

# TODO: I don't think we have any consumers of this anymore?
outputs:
  - name: protobufs

params:
  DEST_DIR: "../protobufs"
  PROTO_INCLUDE: "../plan-protobufs/pkg"

run:
  path: ./build-protobufs
  dir: plan-core
