---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: plan-ci-src
    path: plan-ci
  - name: plan-core-src
    path: plan-core
  - name: plan-protobufs-src
    path: plan-protobufs

outputs:
  - name: protobufs

params:
  DEST_DIR: "../../protobufs"
  PROTO_INCLUDE: "../../plan-protobufs/pkg"

run:
  path: ./build-protobufs
  dir: plan-ci/tasks
