#!/bin/bash
# copies in the protobufs from the previous task

cp ../protobufs/client.pb.go client
cp ../protobufs/pdi/pdi.pb.go pdi
cp ../protobufs/plan/plan.pb.go plan
cp ../protobufs/repo/repo.pb.go repo
cp ../protobufs/ski/ski.pb.go ski

exec make test
