---
# plan-core lint runner

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: plan-ci-src
  - name: plan-core-src
    path: plan-core
  - name: protobufs

run:
  path: /usr/bin/make lint
  dir: plan-core
