#!/bin/bash
set -ex

export GOOS="$GOOS"
export GOARCH="$GOARCH"
export CGO_ENABLED="$CGO_ENABLED"
export GOPATH="$(pwd)/go"
export PATH="${PATH}:${GOPATH}/bin"
export OUTDIR="$(pwd)/builds-${GOOS}"

cd "${WORKDIR}"

go build -o "${OUTDIR}/$1"
