---
# generic builder for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: ((repo))-src
    path: ((repo))
  - name: go
    path: /go

outputs:
  - name: ((repo))

run:
  path: go
  args: ["build", "."]
  dir: ((repo))
