---
# generic linter for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: ((repo))-src
    path: ((repo))
  - name: go
    path: /go

run:
  path: go
  args: ["vet", "."]
  dir: ((repo))
