---
# generic dependencies fetching step for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: plan-ci-src
    path: plan-ci
  - name: ((repo))-src
    path: go/src/github.com/plan-systems/((repo))

outputs:
  - name: go

params:
  WORKDIR: go/src/github.com/plan-systems/((repo))

run:
  path: plan-ci/tasks/gosetup
