#!/bin/bash
# copies in the protobufs from the previous task

# we 'go get' the plan-core input here rather than using the
# automatic invocation so that our protobufs have somewhere
# to land.

go get github.com/plan-systems/plan-core
cp -r ../protobufs/* /go/src/github.com/plan-systems/plan-core

exec go get
