---
# generic builder for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: ((repo))-src
    path: ((repo))
  - name: go
    path: /go

outputs:
  - name: ((repo))

# ref https://github.com/golang/go/blob/master/src/go/build/syslist.go
params:
  GOOS: ((goos))
  GOARCH: ((goarch))

run:
  path: go
  args: ["build", "."]
  dir: ((repo))
