---
# generic linter for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: go
  - name: ((repo))-src
    path: go/src/github.com/plan-systems/((repo))
  # TODO: need to have this here while this isn't go-gettable
  - name: plan-core-src
    path: go/src/github.com/plan-systems/plan-core

params:
  WORKDIR: go/src/github.com/plan-systems/((repo))

run:
  path: go/bin/gopath
  args:
    - "go"
    - "fmt"
    - "./..."
