---
# generic builder for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: go
  - name: ((repo))-src
    path: go/src/github.com/plan-systems/((repo))

outputs:
  - name: builds-((goos))

# ref https://github.com/golang/go/blob/master/src/go/build/syslist.go
params:
  GOOS: ((goos))
  GOARCH: ((goarch))
  CGO_ENABLED: 0
  WORKDIR: go/src/github.com/plan-systems/((repo))

run:
  path: go/bin/gobuild
  args:
    - ((repo))
