---
# generic release builder for a PLAN golang project

platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinistlabs/plan-toolchain-go
    tag: latest

inputs:
  - name: plan-ci-src
  - name: ((repo))-src

outputs:
  - name: ((repo))-dist
    path: dist

caches:
  - path: go/pkg

run:
  path: plan-ci-src/tasks/gopath
  args:
    - "((repo))-src"
    - "make"
    - "release"
